server.port=8080
spring.application.name=backend-challenge

spring.datasource.url = jdbc:postgresql://manny.db.elephantsql.com:5432/htixuwac

spring.datasource.username = htixuwac
spring.datasource.password = Eqf6_QY6SN_0F9LQzkNXLdyqt4nrs_ql
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Connection pool settings (optional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
