server.port=8080
spring.application.name=backend-challenge

#spring.datasource.url = jdbc:postgresql://localhost/postgres
#
#spring.datasource.username = postgres
#spring.datasource.password = 123456
#
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true
#spring.jpa.hibernate.ddl-auto=update